#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'yum'
cookbook 'python'
cookbook 'openssl'
cookbook 'build-essential'
cookbook 'rabbitmq'
cookbook 'mongodb'

cookbook 'checkmate',
  :git => 'https://github.rackspace.com/Cookbooks/checkmate'

cookbook 'rvm',
  :git => 'https://github.com/gondoi/chef-rvm'
