default['checkmate']['rabbitmq']['user'] = "checkmate"
default['checkmate']['rabbitmq']['vhost'] = "/checkmate"

default['checkmate']['local_path'] = "/var/checkmate/chef"
default['checkmate']['chef_repo'] = "/var/checkmate/chef/repo"
default['checkmate']['connection_string'] = "sqlite:////var/checkmate/db.sqlite"
default['checkmate']['broker_username'] = "checkmate"
default['checkmate']['broker_password'] = "checkmate"
default['checkmate']['broker_port'] = "5672"
default['checkmate']['broker_host'] = "localhost"
default['checkmate']['celery_config_module'] = "checkmate.celeryconfig"
default['checkmate']['spiffworkflow_repo'] = "/home/vagrant/Spiff"
default['checkmate']['local_source'] = "/vagrant"
